### ISSUE TITLE
(Bug): MacOS M3 closes on startup 

### ISSUE THREAD

**Issue by Hadis-Fard** [NatronGitHub/Natron#1009] opened 2024-11-03 00:12 UTC
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron-2.5.0-macOS12-x86_64

### Operating system

macOS 14.4 Sonoma

### System specs

RAM 18 GB
Apple Silicon 12 Core
Apple M3 pro 14 GPU core

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

I installed Natron for first time on my new system, on the opening of the app, it crashed and closed, the first screen appears and then immediately crashes, I tried it several times and the issue persists. 

### What did you expect to happen? What happened instead?

Cannot make a screenshot or have a crash number as it just closes after startup 
The issue has been reported for M2 chips as well. #1004 and #998  

### Step-by-step reproduction instructions

1. Installed Natron from installer on M3 pro
2. give apple security permission to open the app as it is marked as unidentified developer (being open source it makes sense)
3. open the Natron
4. *Natron closes

**Comment by devernay** [comment] 2024-11-04 09:08
Known issue, please use https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1

Duplicate of:
- https://github.com/NatronGitHub/Natron/issues/1004
- https://github.com/NatronGitHub/Natron/issues/998
- https://github.com/NatronGitHub/Natron/issues/992
- https://github.com/NatronGitHub/Natron/issues/927 
- https://github.com/NatronGitHub/Natron/issues/874
- https://github.com/NatronGitHub/Natron/issues/737

**Closed as completed by devernay** 2024-11-04 09:08 UTC
Labels: type:bug
