### ISSUE TITLE
(Feature): Vectorscope view mode 

### ISSUE THREAD

**Issue by mini0** [NatronGitHub/Natron#793] opened 2022-05-17 20:49 UTC
### Make sure to follow our issue report guidelines

- [x] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

I think a vectorscope view would make a great addition to a histogram panel. 

### Is this a realistically implementable feature?

- [X] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by devernay** [comment] 2022-05-19 16:32
Duplicate of #79

**Closed as completed by devernay** 2022-05-19 16:32 UTC
Labels: type:feature, status:duplicate
