### ISSUE TITLE
Natron 2.4.2 Crashes on boot (dup of #712)

### ISSUE THREAD

**Issue by blackearth2014** [NatronGitHub/Natron#731] opened 2021-12-22 20:40 UTC
Here is my error log from my mac when I boot Natron 2.4.2 10.15 catalina. 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

<details>
  <summary>Click to expand!</summary>

Process:               Natron [24103]
Path:                  /Users/USER/Desktop/Natron.app/Contents/MacOS/Natron
Identifier:            fr.inria.Natron
Version:               2.4.2 (2.4.2)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-12-22 15:33:49.4709 -0500
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        D68F455C-1EC7-4C56-6975-B6C6C24AB309

Time Awake Since Boot: 120000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000676c6f6a
Exception Codes:       0x0000000000000001, 0x00000000676c6f6a
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [24103]

VM Region Info: 0x676c6f6a is not in any region.  Bytes before following region: 2739347606
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10ab39000-10b9c5000    [ 14.5M] r-x/r-x SM=COW  .../MacOS/Natron

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtGui                         	       0x10d554254 QAction::isEnabled() const + 4
1   QtGui                         	       0x10d53808a qt_mac_set_modal_state_helper_recursive(NSMenu*, NSMenu*, bool) + 570
2   QtGui                         	       0x10d538057 qt_mac_set_modal_state_helper_recursive(NSMenu*, NSMenu*, bool) + 519
3   QtGui                         	       0x10d53dc5b QMenuBarPrivate::macUpdateMenuBarImmediatly() + 2475
4   QtGui                         	       0x10d507adc -[NSApplication(QApplicationIntegration) qt_sendPostedMessage:] + 204
5   QtGui                         	       0x10d507bf3 -[NSApplication(QApplicationIntegration) qt_filterEvent:] + 131
6   QtGui                         	       0x10d507ccb -[QNSApplication sendEvent:] + 59
7   AppKit                        	    0x7ff80ab3b80b -[NSApplication _handleEvent:] + 65
8   AppKit                        	    0x7ff80a70337e -[NSApplication run] + 623
9   QtGui                         	       0x10d511078 QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2040
10  QtCore                        	       0x10ce67518 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 584
11  QtCore                        	       0x10ce6ab8c QCoreApplication::exec() + 188
12  Natron                        	       0x10ac3ef53 Natron::GuiApplicationManager::initGui(Natron::CLArgs const&) + 3795
13  Natron                        	       0x10aeca44f Natron::AppManager::loadInternal(Natron::CLArgs const&) + 1135
14  Natron                        	       0x10aec6cca Natron::AppManager::loadFromArgs(Natron::CLArgs const&) + 890
15  Natron                        	       0x10ab401e0 main + 224
16  dyld                          	       0x1174c24fe start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff807c1e00c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff807c1e00c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff807c1e00c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff807c1e00c start_wqthread + 0

Thread 5:: Global Thread (Pooled) (0x600000574ea8)
0   libsystem_kernel.dylib        	    0x7ff807be8506 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff807c22a89 _pthread_cond_wait + 1224
2   QtCore                        	       0x10cd5a82b QWaitConditionPrivate::wait(unsigned long) + 235
3   QtCore                        	       0x10cd5a707 QWaitCondition::wait(QMutex*, unsigned long) + 87
4   QtCore                        	       0x10cd4b704 QThreadPoolThread::run() + 660
5   QtCore                        	       0x10cd591a8 QThreadPrivate::start(void*) + 376
6   libsystem_pthread.dylib       	    0x7ff807c22514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff807c1e02f thread_start + 15

Thread 6:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	    0x7ff807bede4a __select + 10
1   CoreFoundation                	    0x7ff807d10e1d __CFSocketManager + 630
2   libsystem_pthread.dylib       	    0x7ff807c22514 _pthread_start + 125
3   libsystem_pthread.dylib       	    0x7ff807c1e02f thread_start + 15

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff807be5aba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff807be5e2b mach_msg + 59
2   CoreFoundation                	    0x7ff807ce9a42 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff807ce811b __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff807ce752d CFRunLoopRunSpecific + 563
5   AppKit                        	    0x7ff80a880cec _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff807c22514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff807c1e02f thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000000676c6f62  rbx: 0x00007ff807ab6040  rcx: 0x0000000000000001  rdx: 0x0000000000000000
  rdi: 0x00000000676c6f62  rsi: 0x00007ff8223f64fe  rbp: 0x00007ff7b53c6100  rsp: 0x00007ff7b53c6100
   r8: 0x00007ff849414720   r9: 0x000000000000003f  r10: 0x00007ff84925e080  r11: 0x00007ff80a71ba68
  r12: 0x00007ff8223f64fe  r13: 0x0000600000836740  r14: 0x0000600003b0c230  r15: 0x000000000000000d
  rip: 0x000000010d554254  rfl: 0x0000000000010202  cr2: 0x00000000676c6f6a
  
Logical CPU:     5
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  78 00 48 8b 00 48 85 c0-74 38 8b 8b 10 01 00 00  x.H..H..t8......
  83 e1 fe 41 0f b6 f6 09-f1 66 89 8b 10 01 00 00  ...A.....f......
  ba 28 01 00 00 48 03 50-08 48 89 df e8 cb e1 ff  .(...H.P.H......
  ff 48 89 df 5b 41 5e 5d-e9 7f da ff ff 5b 41 5e  .H..[A^].....[A^
  5d c3 48 8d 3d b5 a8 74-00 31 c0 5b 41 5e 5d e9  ].H.=..t.1.[A^].
  d8 b1 62 00 0f 1f 84 00-00 00 00 00 55 48 89 e5  ..b.........UH..
 [48]8b 47 08 8a 80 10 01-00 00 24 01 5d c3 66 2e  H.G.......$.].f.	<==
  0f 1f 84 00 00 00 00 00-0f 1f 40 00 55 48 89 e5  ..........@.UH..
  41 56 53 48 8b 5f 08 0f-b7 93 10 01 00 00 89 d0  AVSH._..........
  c1 e8 02 83 e0 01 39 c6-75 0c 89 d0 c1 e8 03 83  ......9.u.......
  e0 01 39 c6 75 6d 4c 8b-35 c7 4f 78 00 4d 8b 06  ..9.umL.5.Ox.M..
  4d 85 c0 74 4c 89 f1 80-f1 01 0f b6 c9 c1 e1 03  M..tL...........

Binary Images:
       0x10d4d3000 -        0x10dcd8fff QtGui (*) <f42cacd6-43d6-3782-90d4-48d672208894> /Users/USER/Desktop/Natron.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui
    0x7ff80a6d4000 -     0x7ff80b560fff com.apple.AppKit (6.9) <dd0028a3-78e3-3a8a-a51b-ddd68123adef> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x10cd33000 -        0x10cf8afff QtCore (*) <b4cd581b-5b82-3061-86a0-9da99b676c1d> /Users/USER/Desktop/Natron.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore
       0x10ab39000 -        0x10b9c4fff fr.inria.Natron (2.4.2) <5627c182-4f08-3310-a488-9dac7e308332> /Users/USER/Desktop/Natron.app/Contents/MacOS/Natron
       0x1174bd000 -        0x117528fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld
    0x7ff807c1c000 -     0x7ff807c27fff libsystem_pthread.dylib (*) <29a2750e-f31b-3630-8761-242a6bc3e99e> /usr/lib/system/libsystem_pthread.dylib
    0x7ff807be5000 -     0x7ff807c1bfff libsystem_kernel.dylib (*) <12bd6f13-c452-35ee-9069-51befef29f1a> /usr/lib/system/libsystem_kernel.dylib
    0x7ff807c69000 -     0x7ff80816bfff com.apple.CoreFoundation (6.9) <3002b545-6841-3fc8-91a2-bcfbe5872465> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
ATS (font support)                32.0M       88 
ATS (font support) (reserved)        4K        1         reserved VM address space (unallocated)
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 4800K        4 
CG image                          1044K        3 
ColorSync                          224K       25 
CoreAnimation                     16.4M        3 
CoreGraphics                         4K        1 
CoreUI image data                   60K        1 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           290.3M       60 
MALLOC guard page                   48K       10 
MALLOC_MEDIUM (reserved)         712.0M        6         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        8 
Stack                             19.1M        8 
VM_ALLOCATE                       9164K       59 
__DATA                            47.7M      483 
__DATA_CONST                      19.1M      328 
__DATA_DIRTY                       544K       98 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       685.6M      167 
__OBJC_RO                         81.5M        1 
__OBJC_RW                         3120K        2 
__TEXT                           420.8M      466 
__UNICODE                          588K        1 
dyld private memory               1088K        3 
mapped file                       86.8M       24 
shared memory                     1288K       17 
===========                     =======  ======= 
TOTAL                              2.8G     1876 
TOTAL, minus reserved VM space     1.7G     1876 

-----------
Full Report
-----------

{"app_name":"Natron","timestamp":"2021-12-22 15:33:49.00 -0500","app_version":"2.4.2","slice_uuid":"5627c182-4f08-3310-a488-9dac7e308332","build_version":"2.4.2","platform":1,"bundleID":"fr.inria.Natron","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"CD0F2973-A984-4E63-B69B-4C1B611C1795","name":"Natron"}
{
  "uptime" : 120000,
  "procLaunch" : "2021-12-22 15:33:46.9161 -0500",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac19,1",
  "procStartAbsTime" : 124310150503744,
  "coalitionID" : 8839,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-22 15:33:49.4709 -0500",
  "incident" : "CD0F2973-A984-4E63-B69B-4C1B611C1795",
  "bug_type" : "309",
  "pid" : 24103,
  "procExitAbsTime" : 124312703004815,
  "cpuType" : "X86-64",
  "procName" : "Natron",
  "procPath" : "\/Users\/USER\/Desktop\/Natron.app\/Contents\/MacOS\/Natron",
  "bundleInfo" : {"CFBundleShortVersionString":"2.4.2","CFBundleVersion":"2.4.2","CFBundleIdentifier":"fr.inria.Natron"},
  "storeInfo" : {"deviceIdentifierForVendor":"512516DE-5EF7-5257-89A8-92619F6E7E6A","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "fr.inria.Natron",
  "crashReporterKey" : "D68F455C-1EC7-4C56-6975-B6C6C24AB309",
  "sip" : "enabled",
  "vmRegionInfo" : "0x676c6f6a is not in any region.  Bytes before following region: 2739347606\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10ab39000-10b9c5000    [ 14.5M] r-x\/r-x SM=COW  ...\/MacOS\/Natron",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000000676c6f6a","rawCodes":[1,1735159658],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000676c6f6a"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":24103},
  "vmregioninfo" : "0x676c6f6a is not in any region.  Bytes before following region: 2739347606\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10ab39000-10b9c5000    [ 14.5M] r-x\/r-x SM=COW  ...\/MacOS\/Natron",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":794621,"instructionState":{"instructionStream":{"bytes":[120,0,72,139,0,72,133,192,116,56,139,139,16,1,0,0,131,225,254,65,15,182,246,9,241,102,137,139,16,1,0,0,186,40,1,0,0,72,3,80,8,72,137,223,232,203,225,255,255,72,137,223,91,65,94,93,233,127,218,255,255,91,65,94,93,195,72,141,61,181,168,116,0,49,192,91,65,94,93,233,216,177,98,0,15,31,132,0,0,0,0,0,85,72,137,229,72,139,71,8,138,128,16,1,0,0,36,1,93,195,102,46,15,31,132,0,0,0,0,0,15,31,64,0,85,72,137,229,65,86,83,72,139,95,8,15,183,147,16,1,0,0,137,208,193,232,2,131,224,1,57,198,117,12,137,208,193,232,3,131,224,1,57,198,117,109,76,139,53,199,79,120,0,77,139,6,77,133,192,116,76,137,241,128,241,1,15,182,201,193,225,3],"offset":96}},"threadState":{"r13":{"value":105553124878144},"rax":{"value":1735159650},"rflags":{"value":66050},"cpu":{"value":5},"r14":{"value":105553178182192},"rsi":{"value":140703703196926,"objc-selector":"tag"},"r8":{"value":140704357631776,"symbolLocation":3296,"symbol":"(anonymous namespace)::SideTablesMap"},"cr2":{"value":1735159658},"rdx":{"value":0},"r10":{"value":140704355836032,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSMenuItem"},"r9":{"value":63},"r15":{"value":13},"rbx":{"value":140703257288768,"symbolLocation":0,"symbol":"objc_msgSend"},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":140703303842408,"symbolLocation":0,"symbol":"-[NSMenuItem tag]"},"rip":{"value":4518658644,"matchesCrashFrame":1},"rbp":{"value":140701874282752},"rsp":{"value":140701874282752},"r12":{"value":140703703196926,"objc-selector":"tag"},"rcx":{"value":1},"flavor":"x86_THREAD_STATE","rdi":{"value":1735159650}},"queue":"com.apple.main-thread","frames":[{"imageOffset":528980,"symbol":"QAction::isEnabled() const","symbolLocation":4,"imageIndex":0},{"imageOffset":413834,"symbol":"qt_mac_set_modal_state_helper_recursive(NSMenu*, NSMenu*, bool)","symbolLocation":570,"imageIndex":0},{"imageOffset":413783,"symbol":"qt_mac_set_modal_state_helper_recursive(NSMenu*, NSMenu*, bool)","symbolLocation":519,"imageIndex":0},{"imageOffset":437339,"symbol":"QMenuBarPrivate::macUpdateMenuBarImmediatly()","symbolLocation":2475,"imageIndex":0},{"imageOffset":215772,"symbol":"-[NSApplication(QApplicationIntegration) qt_sendPostedMessage:]","symbolLocation":204,"imageIndex":0},{"imageOffset":216051,"symbol":"-[NSApplication(QApplicationIntegration) qt_filterEvent:]","symbolLocation":131,"imageIndex":0},{"imageOffset":216267,"symbol":"-[QNSApplication sendEvent:]","symbolLocation":59,"imageIndex":0},{"imageOffset":4618251,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":65,"imageIndex":1},{"imageOffset":193406,"symbol":"-[NSApplication run]","symbolLocation":623,"imageIndex":1},{"imageOffset":254072,"symbol":"QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)","symbolLocation":2040,"imageIndex":0},{"imageOffset":1262872,"symbol":"QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)","symbolLocation":584,"imageIndex":2},{"imageOffset":1276812,"symbol":"QCoreApplication::exec()","symbolLocation":188,"imageIndex":2},{"imageOffset":1072979,"symbol":"Natron::GuiApplicationManager::initGui(Natron::CLArgs const&)","symbolLocation":3795,"imageIndex":3},{"imageOffset":3740751,"symbol":"Natron::AppManager::loadInternal(Natron::CLArgs const&)","symbolLocation":1135,"imageIndex":3},{"imageOffset":3726538,"symbol":"Natron::AppManager::loadFromArgs(Natron::CLArgs const&)","symbolLocation":890,"imageIndex":3},{"imageOffset":29152,"symbol":"main","symbolLocation":224,"imageIndex":3},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":4}]},{"id":794636,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":794639,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":794698,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":794699,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":794710,"name":"Global Thread (Pooled) (0x600000574ea8)","frames":[{"imageOffset":13574,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":6},{"imageOffset":27273,"symbol":"_pthread_cond_wait","symbolLocation":1224,"imageIndex":5},{"imageOffset":161835,"symbol":"QWaitConditionPrivate::wait(unsigned long)","symbolLocation":235,"imageIndex":2},{"imageOffset":161543,"symbol":"QWaitCondition::wait(QMutex*, unsigned long)","symbolLocation":87,"imageIndex":2},{"imageOffset":100100,"symbol":"QThreadPoolThread::run()","symbolLocation":660,"imageIndex":2},{"imageOffset":156072,"symbol":"QThreadPrivate::start(void*)","symbolLocation":376,"imageIndex":2},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":794711,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":36426,"symbol":"__select","symbolLocation":10,"imageIndex":6},{"imageOffset":687645,"symbol":"__CFSocketManager","symbolLocation":630,"imageIndex":7},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":794712,"name":"com.apple.NSEventThread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":6},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":6},{"imageOffset":526914,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":7},{"imageOffset":520475,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":7},{"imageOffset":517421,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":7},{"imageOffset":1756396,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":1},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4518129664,
    "size" : 8413184,
    "uuid" : "f42cacd6-43d6-3782-90d4-48d672208894",
    "path" : "\/Users\/USER\/Desktop\/Natron.app\/Contents\/Frameworks\/QtGui.framework\/Versions\/4\/QtGui",
    "name" : "QtGui"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703303548928,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15257600,
    "uuid" : "dd0028a3-78e3-3a8a-a51b-ddd68123adef",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4510134272,
    "size" : 2457600,
    "uuid" : "b4cd581b-5b82-3061-86a0-9da99b676c1d",
    "path" : "\/Users\/USER\/Desktop\/Natron.app\/Contents\/Frameworks\/QtCore.framework\/Versions\/4\/QtCore",
    "name" : "QtCore"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4474507264,
    "CFBundleShortVersionString" : "2.4.2",
    "CFBundleIdentifier" : "fr.inria.Natron",
    "size" : 15253504,
    "uuid" : "5627c182-4f08-3310-a488-9dac7e308332",
    "path" : "\/Users\/USER\/Desktop\/Natron.app\/Contents\/MacOS\/Natron",
    "name" : "Natron",
    "CFBundleVersion" : "2.4.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4685811712,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703258755072,
    "size" : 49152,
    "uuid" : "29a2750e-f31b-3630-8761-242a6bc3e99e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703258529792,
    "size" : 225280,
    "uuid" : "12bd6f13-c452-35ee-9069-51befef29f1a",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703259070464,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "3002b545-6841-3fc8-91a2-bcfbe5872465",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 140703255527424,
  "size" : 15213641728,
  "uuid" : "3d05845f-3f65-358f-9ebf-2236e772ac01"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=1.4G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nATS (font support)                32.0M       88 \nATS (font support) (reserved)        4K        1         reserved VM address space (unallocated)\nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 4800K        4 \nCG image                          1044K        3 \nColorSync                          224K       25 \nCoreAnimation                     16.4M        3 \nCoreGraphics                         4K        1 \nCoreUI image data                   60K        1 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           290.3M       60 \nMALLOC guard page                   48K       10 \nMALLOC_MEDIUM (reserved)         712.0M        6         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        8 \nStack                             19.1M        8 \nVM_ALLOCATE                       9164K       59 \n__DATA                            47.7M      483 \n__DATA_CONST                      19.1M      328 \n__DATA_DIRTY                       544K       98 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       685.6M      167 \n__OBJC_RO                         81.5M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           420.8M      466 \n__UNICODE                          588K        1 \ndyld private memory               1088K        3 \nmapped file                       86.8M       24 \nshared memory                     1288K       17 \n===========                     =======  ======= \nTOTAL                              2.8G     1876 \nTOTAL, minus reserved VM space     1.7G     1876 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "614a34c5eae97a2111628dc5"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000185
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000090
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61b913a253a0785760dd8bbb"
      },
      "deploymentId" : 240000355
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac19,1, BootROM 1715.40.15.0.0, 6 processors, 6-Core Intel Core i5, 3.7 GHz, 64 GB, SMC 2.46f12
Graphics: Radeon Pro Vega 48, Radeon Pro Vega 48, PCIe, 8 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, 16ATF2G64HZ-2G6E3
Memory Module: BANK 1/ChannelA-DIMM1, 16 GB, DDR4, 2667 MHz, Micron, 16ATF2G64HZ-2G6E3
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, 16ATF2G64HZ-2G6E3
Memory Module: BANK 3/ChannelB-DIMM1, 16 GB, DDR4, 2667 MHz, Micron, 16ATF2G64HZ-2G6E3
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 12 2021 19:26:30 version 9.30.464.0.32.5.76 FWID 01-45ccefcd
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE HDD ST3000DM001, 3 TB
USB Device: USB31Bus
USB Device: M4
USB Device: FaceTime HD Camera (Built-in)
USB Device: hub_device
USB Device: Dell MS116 USB Optical Mouse
USB Device: Magic Keyboard with Numeric Keypad
USB Device: Rugged USB-C
USB Device: d2 TBT2 USB 3.0
Thunderbolt Bus: iMac, Apple Inc., 47.5
</details>

**Comment by devernay** [comment] 2021-12-22 20:46
That's a duplicate of #712

You are running Monterey, which will be a serious issue for Natron until we switch to using Qt5. Monterey is not recommended for production use (Big Sur seems OK) 

When you say "on boot", is that when double-clicking on a project, or when double-clicking on Natron and then opening a project from there?

Note: editing your report to make it collapsible, see https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab to learn how to do it

**Comment by blackearth2014** [comment] 2021-12-22 21:44
Yes it crashes when I double click on it.

**Comment by devernay** [comment] 2021-12-23 01:20
Does it crash before showing anything, or after the splashscreen closes?

Did you test with the macOS12 binary?

**Comment by devernay** [comment] 2022-01-08 02:26
duplicate of #712

**Closed as completed by devernay** 2022-01-08 02:26 UTC
Labels: status:duplicate

**Comment by blackearth2014** [comment] 2022-01-21 09:32
> 

No I did not. I have been on vacation from work. Will test today when I get in.
