### ISSUE TITLE
Roto node keyframes never appear on Dope Sheet

### ISSUE THREAD

**Issue by nvmb3rth30ry** [NatronGitHub/Natron#307] opened 2018-10-02 12:01 UTC
### Problem
Keyframes created by the _Roto_ node never seem to be included on the **Dope Sheet**. This makes shifting Roto keyframes along the timeline nearly impossible. 

**Expected behavior:**
After a keyframe is created for the _Roto_ node, I expect to see it appear on the Dope Sheet pane, and be able to manipulate it there as with all other animation keyframes.

**Actual behavior:** 
After making a _Roto_ node keyframe animation, when I view the Dope Sheet pane, the _Roto_ node (and its keyframes) do not appear. This is easily reproducible through very simple tests of _Roto_ node animation.

### Steps to Reproduce

1. Make a project
2. Add a _Roto_ node and a background such as _Checkerboard_  
3. Make a shape from the Roto and animate a few changes to it over several frames
4. Check the Dope Sheet pane for changes 

### Versions
* **Natron version 23.1.13** 
* **OS version: Ubuntu 18.04.1 LTS**

**Comment by tobiasBora** [comment] 2020-11-25 15:50
I can confirm, any news on this? I don't see how it's possible to use reliably roto without this feature.

**Comment by rodlie** [comment] 2020-11-26 12:38
No news sadly, we lack developers ...

I will start doing stuff again next month during my vacation (I got ~2 weeks free), but the todo list is big and I can't guarantee that this issue will be worked on (this year).

**Comment by Shrinks99** [comment] 2021-05-10 19:58
@Echolon This appears to be a duplicate of #146.

**Comment by Echolon** [comment] 2021-05-28 07:20
Alright - I will close this!

**Comment by Echolon** [comment] 2021-05-28 07:20
@devernay evtl. adjust the milestones correctly

**Closed by Echolon** 2021-05-28 07:20 UTC
Labels: difficulty:medium, func:gui, prio:low, status:duplicate, type:feature
