### ISSUE TITLE
(Bug): UNC Path Support in File Dialogs

### ISSUE THREAD

**Issue by joshdicarlo** [NatronGitHub/Natron#896] opened 2023-06-17 00:32 UTC
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [X] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5

### Operating system

Windows 10 Professional

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Read, Write, Load Project, or Save Project from network location with UNC path. 

In various file dialogs, type a UNC base path matching one confirmed to load when manually typed on a Read node. 

Ex: 
- Read node path "//my_network_share/project/sequence/shot/shot_name.mp4" will playback correctly
- Typing "//my_network_share/project/sequence/shot" into the "Open Sequence" or "Save Seqeuence" dialog that appears when creating a read or write node will not browse to that location - making it very difficult to operate in a network environment on windows. 

### What did you expect to happen? What happened instead?

What did I expect to happen:

- Typing "//my_network_share/project/sequence/shot" into the "Open Sequence" or "Save Seqeuence" dialog should browse to that location, just as it does when typing "C:/Users/username"

What happened instead:
- Nothing

### Step-by-step reproduction instructions

1. Create a Read Node OR Create a Write Node OR File>Open Project OR File>Save Project
2. In the file dialog dialog, type a valid UNC path and press enter

### Additional details

Note: I am filing this as a bug, since UNC paths are clearly supported in various nodes, but the file dialog's won't browse to them leading me to believe this is a bug. 

It is clear that UNC paths are supported from https://github.com/NatronGitHub/Natron/issues/302, and upon testing a Read/Write Node can be manually provided a UNC path, and will successfully read/write from/to it. 

Issue persists with with both forward or backward slashes. 

Dialog's include:
* Open Sequence (Read Node)
* Save Sequence (Write Note)
* Save File (File>Save Project As...)
* Open File (File>Open Project...)

In a studio environment, custom drive letter mappings are not an option so UNC path support is important.

**Comment by f-dy** [comment] 2023-06-17 00:38
can you please try if the bug is also in 2.6 alpha? https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1

Is it the same bug as https://github.com/NatronGitHub/Natron/issues/236 ?

**Comment by joshdicarlo** [comment] 2023-06-17 00:45
I can try 2.6 Alpha. 

While it's possible they are related - this is not the same bug as #236  - which appears to focus on OpenColorIO and underlying symlink support for UNC paths - which could be entirely related to OCIO and not Natron itself. 

This bug is directly related to Natron's native file dialogs, where locations on a file server are inaccessible to browse to using UNC paths.

**Comment by joshdicarlo** [comment] 2023-06-17 00:55
I tried installing the Alpha but was unable to launch it. I received 4 system errors after multiple installation attempts. 
![Snag_7d53c2ee](https://github.com/NatronGitHub/Natron/assets/18133278/a47ff379-b3cb-45a9-ad86-872c8139ad3e)
![Snag_7d53ccb2](https://github.com/NatronGitHub/Natron/assets/18133278/447c60e5-f79e-4e94-88f4-b908c71794a9)
![Snag_7d53d4a1](https://github.com/NatronGitHub/Natron/assets/18133278/9eeb244f-883b-441b-9dcf-790bc87b8a37)
![Snag_7d53dcc0](https://github.com/NatronGitHub/Natron/assets/18133278/4aac7a66-ed18-47e0-af93-439d97bcde35)

**Comment by f-dy** [comment] 2023-06-17 01:13
@acolwell for the issue with the 2.6 build

**Comment by acolwell** [comment] 2023-06-17 14:55
So I have verified that explicitly providing a full path to a file on a network share works, but providing a directory on a share does not allow you to browse the directory. I'm looking into the cause of this right now.

I am not able to reproduce the missing DLL errors though. The alpha build in [Natron-RB-2.6-202305242302-b9a9b81-Windows-x86_64.zip](https://github.com/NatronGitHub/Natron/releases/download/v2.6.0-alpha1/Natron-RB-2.6-202305242302-b9a9b81-Windows-x86_64.zip) installs and runs fine for me on Windows 10 Pro. Those DLLs mentioned in the error dialogs are in the zip file and should be getting copied to the installed directory. 
- Where are you installing Natron? 
- Do you see these DLLs in the bin directory of your install location? (Typically C:\Program Files\Natron\bin for "all users install" or something like C:\Users\aaron\AppData\Local\Programs\Natron\bin for "single user" install)
- If the DLLs are not present, does it work if you copy these DLLs from the zip file bin directory to your install bin directory?
- Do you still see these errors if you just unzip the file and run the Natron.exe in the unzipped bin directory?

**Comment by acolwell** [comment] 2023-09-11 15:21
The fix for this in #901 just landed. It will be available in the next Natron release.

**Closed as completed by acolwell** 2023-09-11 15:21 UTC
Labels: type:bug
