### ISSUE TITLE
Natron doesn't read mp4 files.

### ISSUE THREAD

**Issue by Danika207** [NatronGitHub/Natron#528] opened 2020-07-24 14:00 UTC
### Whenever I try to import a mp4 (or basically any other file) to the Read node, It puts out an error:
_"Error while creating node for fr.inria.build-in.Read: Could not find a decoder to read mp4 file format"_

_**The error can be easily reproduced**_ by importing a video (using the Read node) in a new empty project.
(_**Although it seems pointless**_ if you don't get an error when doing that.)

_And it doesn't crash, just writes an errors in the console._

**Natron version:** (Tried 2.3.14, 2.3.15, 2.3.16)
**OS version:** Windows 7 64-bit

In the console it says something about the IO.ofx.bundle OpenFx plugin is required, make sure you installed this.
I tried reinstalling the program (with different versions also, as you can see by the "Natron versions")

**I can send further images about the console, if needed.**

(Full console text)
"Error while creating node for fr.inria.build-in.Read: Could not find a decoder to read mp4 file format"
"Error while creating node fr.inria.build-in.Read: The IO.ofx.bundle OpenFx plugin is required to use this node, make sure it is installed."

**Comment by rodlie** [comment] 2020-07-24 14:05
Windows 7 is not supported anymore, see issue #526 for more information (and workaround).

Closed as duplicate of #526

**Closed by rodlie** 2020-07-24 14:05 UTC
