### ISSUE TITLE
(Bug): Mac Studio, M2 MAX Chip, Crashes at start

### ISSUE THREAD

**Issue by SImon81de** [NatronGitHub/Natron#1004] opened 2024-10-08 07:50 UTC
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Sonoma 14.3.1 (23D60) 

### System specs

Apple M2 Max, 32 GB

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

Starting the program

### What did you expect to happen? What happened instead?

Running the program

### Step-by-step reproduction instructions

Downloaded Natron-2.5.0-macOS12-x86_64.dmg from Website
Copied to Program folder (2x security override from Apple, open .dmg and start program)
Started Program
Program is loading until interface with nodetree is visible.
Crash immediately.

Retryed. Restartet system.
Download Natron-2.5.0-macOS1015-x86_64.dmg
Copied to Program folder (2x security override from Apple, open .dmg and start program)
Started Program
Loading until interface with nodetree is visible.
Crashs immediately AFTER mouse was moved.
So, as long the mouse is not touched, Natron is alive.

Best regards

**Comment by devernay** [comment] 2024-10-08 08:34
Known issue, please use https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1

Duplicate of:
- https://github.com/NatronGitHub/Natron/issues/998
- https://github.com/NatronGitHub/Natron/issues/992
- https://github.com/NatronGitHub/Natron/issues/927 
- https://github.com/NatronGitHub/Natron/issues/874
- https://github.com/NatronGitHub/Natron/issues/737

**Closed as completed by devernay** 2024-10-08 08:34 UTC
Labels: type:bug
