### ISSUE TITLE
Natron Text Node Horizontal align not working

### ISSUE THREAD

**Issue by mnhan32** [NatronGitHub/Natron#304] opened 2018-09-13 15:49 UTC
Text node Horizontal align only align to Left, rest of options are not working.
It will also be great if there is an option to overlay text directly onto source input, instead of using Merge node. Source input of text node seems only to provide  size info.

Natron 2.3.14
Archlinux x64

**Comment by ivan-avalos** [comment] 2019-05-19 02:52
I have the same problem, it doesn't seem to have been solved yet.

**Comment by rodlie** [comment] 2019-06-07 23:34
TextFX does not support input since I had to do that through Cairo and if I remember right had some issues.

Also, remember that TextFX is a rather complex plugin and some options require other options to work. I will however check the plugin and see if it's a bug.

I also recommend using the Pango Markup language for better control over the text layout.

@devernay : I have made a text editor for pango markup (basically html<->pango) in https://github.com/rodlie/cyan, this is something to consider adding in Natron, that will give TextFX "WYSIWYG" functions. Will of course need to be integrated in Natron and added to openfx as an "rich-text" option or something.
![TextFX-editor](https://user-images.githubusercontent.com/34516798/59138420-4e62c280-898d-11e9-8dec-0ba8dd89370b.png)

**Comment by rodlie** [comment] 2019-06-08 03:00
(Horizontal) align is disabled if custom position is enabled. This is not an bug.

Docoumentation: https://natron.readthedocs.io/en/rb-2.3/plugins/net.fxarena.openfx.Text.html

**Comment by devernay** [comment] 2019-06-08 05:12
btw this patch was integrated in IM: https://github.com/ImageMagick/ImageMagick/issues/1488

**Comment by devernay** [comment] 2019-06-08 05:12
(this patch is from you, Ole)

**Comment by rodlie** [comment] 2019-06-08 05:35
I know (forgot about that), I have more pango patches from Cyan for ImageMagick (when I get the time). Note that TextFX does not use ImageMagick, only the old one we don't use anymore.

**Comment by rodlie** [comment] 2019-06-27 23:51
I updated the description for align in TextFX.

Horizontal align works only when:
* Custom position is disabled (Transform)
* Auto size is disabled 
* Word wrap is **not** None

**Comment by rodlie** [comment] 2019-08-08 13:03
Closing as this was not a bug, just poor documentation on my side.

**Closed by rodlie** 2019-08-08 13:03 UTC
Labels: difficulty:easy, func:plugins, type:bug
