### ISSUE TITLE
(Bug): errors with ffmpeg5

### ISSUE THREAD

**Issue by a61kt** [NatronGitHub/Natron#797] opened 2022-06-02 01:11 UTC
### Make sure to follow our issue report guidelines

- [ ] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

2.4.3

### Operating system

manjaro/garuda

### System specs

ram 16gb
cpu fx 8350
gpu rx 560

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [X] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### Custom installation path

no

### What were you trying to do?

i try to build natron (openfx-io)

and openfx-io its broken

buildlog there
https://builds.garudalinux.org/repos/chaotic-aur/logs/openfx-io.log

### What did you expect to happen? What happened instead?

a successful compilation + working binary  

### Step-by-step reproduction instructions

just try to build openfx-io  on arch  (with ffmpeg5)

### Additional details

nothing

**Comment by rodlie** [comment] 2022-06-02 06:50
Duplicate of https://github.com/NatronGitHub/openfx-io/issues/22.

**Closed as completed by rodlie** 2022-06-02 06:50 UTC
Labels: type:bug
