### ISSUE TITLE
(Bug): 

### ISSUE THREAD

**Issue by andrebelluci** [NatronGitHub/Natron#876] opened 2023-04-26 21:42 UTC
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

macOS Monterey 12.6.5

### System specs

MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Processor 2 GHz Quad-Core Intel Core i5
Memory 16 GB 3733 MHz LPDDR4X
Graphics Intel Iris Plus Graphics 1536 MB

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

If I try to change the color of a Roto, the application crash. Both buttons, Ok or Cancel crash the app.

### What did you expect to happen? What happened instead?

<img width="1427" alt="Screen Shot 2023-04-26 at 17 37 55" src="https://user-images.githubusercontent.com/1045892/234709225-2245ff4d-a43c-458a-8c6f-c6244daebaf8.png">

### Step-by-step reproduction instructions

1. Open Natron
2. Create a Roto
3. Draw a element
4. Change color in Channel
5. Click OK or CANCEL
6. Crash

**Comment by devernay** [comment] 2023-05-07 17:05
Duplicate of https://github.com/NatronGitHub/Natron/issues/712
Please try the Qt5 version (Natron 2.6 alpha https://github.com/NatronGitHub/Natron/releases/tag/v2.6.0-alpha1) and report in #712

**Closed as completed by devernay** 2023-05-07 17:05 UTC
Labels: type:bug, status:duplicate
