### ISSUE TITLE
Random freeze when rendering

### ISSUE THREAD

**Issue by Ivanohe73** [NatronGitHub/Natron#417] opened 2019-08-06 03:03 UTC
The docker build sometime freeze on the Natron2_BayMaxProject_20_fixed_switched.ntp and some other project. 
see (https://discuss.pixls.us/t/compiling-natron-yourself-using-the-docker-sdk/13474/4)

It is possible to reproduce it in Gui or with NatronRenderer with version 2.3.15rc6. The problem show about 1 out of 8 time when doing it this way.

### Steps to Reproduce

Running many time the rendering of BayMax switched project will produce a freeze at some point (deadlock I presume)

#!/bin/bash
for i in {1..30}
do
   echo "loop $i"
   ./NatronRenderer --clear-cache -b -w WriteOIIO1 1-40 ~/Natron-Tests/BayMax/Natron2_BayMaxProject_20_fixed_switched.ntp 
done

It is also possible in the Natron Gui to get a similar freeze when playing back the project. I get it when playing with the transport button (play, rewind) a lot. Once it occur, the transport button are not responsive any more

I have a test project that also cause this issue, and this project has a switch node in it, like this BayMax_switched project.

NOTE : It is not related to issue #416 : using an older Misc plugin (from a Natron 2.3.14 won't solve the rendering freeze issue)

Using Natron 2.3.14, I cannot reproduce the freeze.

The test is at :
https://github.com/NatronGitHub/Natron-Tests/tree/master/BayMax
The asset for the Robot are at
https://sourceforge.net/projects/natron/files/Examples/Natron_2.3.12_BayMax.zip/download

### Versions

* **2.3.15rc6**
* **Centos 7.6**

**Comment by Ivanohe73** [comment] 2019-08-06 14:56
backtrace once the problem occurs : 
[natron_bt2.txt](https://github.com/NatronGitHub/Natron/files/3472869/natron_bt2.txt)

**Comment by devernay** [comment] 2019-08-06 19:31
It's probably related to the GIL stuff.

I tried to disable the "Natron" GIL, which was a handmade fix for when we didn't know how to properly use the Python GIL (in commit https://github.com/NatronGitHub/Natron/commit/d931497fd631d614fa722ffada71a38b4e8de4c2).

Please test again

related commits:
https://github.com/NatronGitHub/Natron/commit/c76e9eb3815fb9bc87f1e92e1a70db2a24793b9f
https://github.com/NatronGitHub/Natron/commit/5626618b524ed6fe40f82c2002c3a3873e7e07da
https://github.com/NatronGitHub/Natron/commit/d931497fd631d614fa722ffada71a38b4e8de4c2

related issues:
https://github.com/NatronGitHub/Natron/issues/379

**Comment by devernay** [comment] 2019-08-06 19:34
reopened, please test and report

**Comment by Ivanohe73** [comment] 2019-08-06 19:53
I got this error that I fixed locally with the following patch (just an endif moved)

AppManager.cpp: In destructor 'Natron::PythonGILLocker::~PythonGILLocker()':
AppManager.cpp:4245:17: error: 'class Natron::AppManager' has no member named 'releaseNatronGIL'
 4245 |         appPTR->releaseNatronGIL();
      |                 ^~~~~~~~~~~~~~~~

```
diff --git a/Engine/AppManager.cpp b/Engine/AppManager.cpp
index 70c0947ca..008313349 100644
--- a/Engine/AppManager.cpp
+++ b/Engine/AppManager.cpp
@@ -4241,8 +4241,8 @@ PythonGILLocker::~PythonGILLocker()
 #ifdef DEBUG_PYTHON_GIL
         qDebug() << QString::fromUtf8("Thread '%1' is releasing the Natron GIL (%2)").arg(threadname).arg(natronCount[threadname]);
         --natronCount[threadname];
-#endif
         appPTR->releaseNatronGIL();
+#endif
     }
 
     // We took the Python GIL too, so release it here.

```
I should be able to test it soon if not other error occurs while building

**Comment by devernay** [comment] 2019-08-06 19:56
From the backtrace:
- thread 21 is waiting for the GIL to evaluate an expression, and is blocked on PyThread_acquire_lock
- thread 2 is also blocked on PyThread_acquire_lock, but it should already have the GIL taken by KnobHelper::executeExpression a few frames up

If you can reproduce this, can you please try the recipe at https://stackoverflow.com/questions/42169768/debug-pythread-acquire-lock-deadlock and try to get more debug info?

**Comment by Ivanohe73** [comment] 2019-08-06 20:43
Some bad news : The latest version from git show a similar freeze. However this look more like a busy loop than a deadlock since the process run steady at 30% cpu but no more frame are produced.

I attach a backtrace of this in case. Note : I am trying the recipe for the python backtrace but got some issue that I am trying to resolve. I followed instruction for Centos but can't seems to make the py backtrace work.

[natron_bt_spining_.txt](https://github.com/NatronGitHub/Natron/files/3474072/natron_bt_spining_.txt)

**Comment by Ivanohe73** [comment] 2019-08-06 20:58
Doing Ctrl-C with the latest code, I can get the NatronRenderer to exit properly (which is not the case with previous version). I got those trace in case it can give some hint : 

```
WriteOIIO1 ==> Frame: 8, Progress: 55.0%, 0.8 Fps, Time Remaining: 22 seconds 
WriteOIIO1 ==> Frame: 9, Progress: 57.5%, 0.8 Fps, Time Remaining: 20 seconds
^C
Caught termination signal, exiting!
Render aborted
Render aborted
Render aborted
Unrenderer pixels in the following region: 
x1 = 0 y1 = 0 x2 = 959 y2 = 539
Render aborted
Render aborted
Render aborted
Unrenderer pixels in the following region: 
x1 = 0 y1 = 0 x2 = 959 y2 = 539
Render aborted
Render aborted
Unrenderer pixels in the following region: 
x1 = 0 y1 = 0 x2 = 959 y2 = 539
Unrenderer pixels in the following region: 
x1 = 0 y1 = 0 x2 = 959 y2 = 539
Unrenderer pixels in the following region: 
x1 = 0 y1 = 0 x2 = 959 y2 = 539
Render aborted
Render aborted
Render aborted
Unrenderer pixels in the following region: 
x1 = 0 y1 = 0 x2 = 959 y2 = 539
Render aborted
WriteOIIO1 ==> Rendering finished
"Thread 'Main' is asking the Python GIL" 
"Thread 'Main' got the Python GIL" 
Finalizing Python 

```

I also realize the patch I made in order to compile is probably not correct. should possibly add some #ifdef DEBUG_NATRON_GIL around the AppManager.cpp:4245 . But as I see, this seems to run only at termination so I don't think my patch cause this spining issue

**Comment by Ivanohe73** [comment] 2019-08-06 22:02
I will try to do build of some git version between 2.3.14 and now, so see at what version it start to have the freeze problem. just to be sure it is not something else than what you are suspecting

**Comment by devernay** [comment] 2019-08-06 22:08
you can just try before https://github.com/NatronGitHub/Natron/commit/c76e9eb3815fb9bc87f1e92e1a70db2a24793b9f
- if it works then the GIL stuff is the issue.: try https://github.com/NatronGitHub/Natron/commit/5626618b524ed6fe40f82c2002c3a3873e7e07da (after the GIL change was completed) and if it fails, then the GIL stuff is definitely the issue
- if it fails, then that's an earlier change

**Comment by devernay** [comment] 2019-08-06 22:09
the commit before c76e9eb is https://github.com/NatronGitHub/Natron/commit/9cfd97ee9a69fd176cb24a8c0f05ef64255d4624

**Comment by devernay** [comment] 2019-08-06 22:42
It may also be an OpenImageIO issue... you should also try building v2.3.14 with the current SDK. If it also hangs, then the culprid is probably OIIO

**Comment by devernay** [comment] 2019-08-06 22:50
or it can be OpenEXR.

> [natron_bt_spining_.txt](https://github.com/NatronGitHub/Natron/files/3474072/natron_bt_spining_.txt)

I see that only thread 3 is running in this bt.

There are bugs in the Natron 2 cache (and the "trimap" system), which is why we rewrote it from scratch at some point (see the master branch), but never got a finished version.

What I would recommend is to limit the number of threads in the Natron preferences, which reduces the chances too hit these bugs.

**Comment by Ivanohe73** [comment] 2019-08-07 17:27
Good news : I installed the new v2.3.15rc7 and got no freeze!

I run the rendering of the project many time on 4 different machines.
1 CentOS 6.4 (ivy bridge  i7-3615QE CPU @ 2.30GHz)
3 CentOs 7.6 (i7-5930K CPU @ 3.50GHz, and 2 haswel i7-4860EQ CPU @ 1.80GHz)

I run about 300 rendering without issue.

To be sure, I retest with 2.3.15rc6 and got some freeze. Usually I got a freeze one out of 15 rendering.

I noticed a drop of performance compared to rc6 or 2.3.14. (maybe rc7 is optimized differently?)

As for the spinning problem I got yesterday, it could be that I didn't build the same version or more probably that my build had issue (I was not using the docker build since I was trying to create older version that fail under docker)...

**Comment by devernay** [comment] 2019-08-07 18:58
Il the freeze disappears, then it was probably due to the "Natron GIL" which I removed since we now use the Python GIL correctly. Let us hope I didn't introduce any new race condition...

You might want to adjust the preferences for Threading->Number of render threads and Threading->Number of parallel renders. See the default value in the tooltip for the "Number of render threads" (which is the most important parameter.

The performance drop is probably due to the fact that Natron is using too many threads. Since I removed the "Natron GIL" which is a mutex, more threads are running simultaneously, and this is probably asking too much out of it.

On systems with many hyperthreaded cores, you may get twice the number of cores as the default value, which may sum up to 32 threads for a 16-core system. Unfortunately, this doesn't take into account the overhead of data and memory transfers, so the optimal value for compositing may be below this.
What I would recommend is to tweak the "Number of render threads" until you get maximum CPU utilization on your system on a typical compositing project (eg Baymax or Spaceship).

What does `lscpu` say on your systems for the following:
- Thread(s) per core
- Core(s) per socket
- Socket(s)

I seriously think we may want to change that default for the "number of render threads" in Natron, to use sockets*cores instead of sockets*cores*threads_per_core

**Comment by Ivanohe73** [comment] 2019-08-07 19:19
I have on my main machine
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1

and on the haswel : 
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1

I am trying some value for " Number of render threads" and "Number of parallel renders" to see if I can get better result

**Comment by Ivanohe73** [comment] 2019-08-07 20:17
I tried many combination of the threads setting without getting better than the default one. here is my data in case it is of interest 

[natron_render_thread_test.txt](https://github.com/NatronGitHub/Natron/files/3478728/natron_render_thread_test.txt)

I guess we'll have to live with the hit of performance. Still better than random freeze :)

**Comment by devernay** [comment] 2019-08-08 03:44
closing this issue for now

**Closed by devernay** 2019-08-08 03:44 UTC
Labels: func:engine, func:python, info:feedback-needed, prio:high
