### ISSUE TITLE
LensDistortion issue in Natron 2.3.15rc6

### ISSUE THREAD

**Issue by Ivanohe73** [NatronGitHub/Natron#416] opened 2019-08-06 02:06 UTC
The test project Natron2_BayMaxProject_20_fixed_switched.ntp with the latest Natron (2.3.15rc6) has some problem with the LensDistortion node : 

* A new warning show when loading the project :  Project: WARNING: The node LensDistortion (net.sf.openfx.LensDistortion) version 2.0 was found in the script but was loaded with version 4.0 instead.

* only one corner of the image appear and it is stretched. This occur for frame 1-10 and 37 to end.

![natron_bug](https://user-images.githubusercontent.com/52424403/62506020-ebdf4480-b7cc-11e9-8bcd-932db73ba3fa.png)

Disabling the LensDistortion node make the image look good again.

It work good on Natron 2.3.14

Also, If I copy the Misc plugins from 2.3.14 to 2.3.15rc6 it work correct. This means the problem is only in the plugin, not in Natron

The test is at :
https://github.com/NatronGitHub/Natron-Tests/tree/master/BayMax
The asset for the Robot are at 
https://sourceforge.net/projects/natron/files/Examples/Natron_2.3.12_BayMax.zip/download

### Versions

* **2.3.15rc6**
* **CentOS 7.6**

**Comment by devernay** [comment] 2019-08-06 06:17
Does the warning also appear in 2.3 14?
I think the issue is not related to lensdistortion. Probe the project u using 2.3.14 and 2.3.15 using the viewer and see where they diverge

**Comment by Ivanohe73** [comment] 2019-08-06 13:52
This warning only appear in 2.3.15rc6. I diff the 2 warning list to be sure. 

2.3.14 vs 2.3.15rc6 before lensdistortion : 

![snapshot_before_lens](https://user-images.githubusercontent.com/52424403/62545489-ca637480-b82f-11e9-8572-09cbde6df587.png)


2.3.14 vs 2.3.15rc6 after lensdistortion : 

![snapshot_after_lens](https://user-images.githubusercontent.com/52424403/62545498-cfc0bf00-b82f-11e9-940f-44f3941c55dc.png)

**Comment by devernay** [comment] 2019-08-06 16:28
You nailed it @Ivanohe73 !
I removed by mistake versions 2 and 3 when testing the Fusion issues: https://github.com/NatronGitHub/openfx-misc/commit/8475347fc16a659f509170461ac2608bf1120624#r34591245

Will be fixed in the next version.
Thank you Yves. I think the unit test reporting should be improved, eg when BayMax fails we should also get the error log.

**Closed** 2019-08-06 16:31 UTC

**Comment by Ivanohe73** [comment] 2019-08-06 19:41
Great!
