### ISSUE TITLE
RGBtoHSL doesn't work properly with pure white color

### ISSUE THREAD

**Issue by lehuan5062** [NatronGitHub/Natron#512] opened 2020-06-17 02:16 UTC
### Problem

**Expected behavior:**
RGBtoHSL should convert white color to the stable result which can be seen in other software.

**Actual behavior:**
The result is different.

### Steps to Reproduce

1. Create a white constant.
2. Connect to the RGBtoHSL node and view the result.
3. Here is the comparison with Nuke and Fusion:
 - Natron (has a warning):
![image](https://user-images.githubusercontent.com/65440815/84846882-fff50300-b079-11ea-841f-4f72956c7374.png)
- Nuke:
![image](https://user-images.githubusercontent.com/65440815/84846908-0e431f00-b07a-11ea-8387-f575e9fab5db.png)
- Fusion:
![image](https://user-images.githubusercontent.com/65440815/84846936-1e5afe80-b07a-11ea-91f1-c5c726742b98.png)

I know that RGBtoHSL doesn't apply gamma correction like Nuke and Fusion, but the result is only different in the pure white color. Another comparison that contain other color than white:
- Natron (has a warning): https://cdn.discordapp.com/attachments/416187415879876612/722369172016857128/unknown.png
- Nuke: https://cdn.discordapp.com/attachments/416187415879876612/722349348993761320/unknown.png
- Fusion: https://cdn.discordapp.com/attachments/416187415879876612/722352511146786856/unknown.png

The only difference between Natron and the others is the logo at the bottom right corner. It's originally pure white. Here is the closer view of Natron result: https://cdn.discordapp.com/attachments/416187415879876612/722369471645220884/unknown.png

The edge of the logo blended with other color, it's not pure white so the conversion seems to be corrected. But the inside is pure white. This is the value: https://cdn.discordapp.com/attachments/416187415879876612/722370636110102579/unknown.png

### Versions

* **Natron version/commit**: 2.3.16 beta 1
* **OS version:** Windows 10

**Comment by lehuan5062** [comment] 2020-06-17 02:40
I don't know if it is related to #513

**Comment by devernay** [comment] 2020-06-17 06:38
no it's not; fix is commited, will be in the next beta (2.3.16beta2)

**Comment by lehuan5062** [comment] 2020-06-17 06:46
great, thank you!

**Comment by Shrinks99** [comment] 2021-03-13 22:25
Confirmed fixed in beta 2, the RGB --> HSL conversion still delivers different results than Nuke (presumably because of gamma correction, converting to sRGB before using RGBToHSL gives very similar results) however this fix works as expected and I think this issue can be closed! :D

**Comment by devernay** [comment] 2021-03-13 22:49
thanks!
fixed by https://github.com/NatronGitHub/openfx-supportext/commit/0a01bd898ea3ab24af3a56970f05871d74e4a4ca

**Closed by devernay** 2021-03-13 22:49 UTC
Labels: difficulty:easy, func:plugins, status:fix-commited, type:bug
