### ISSUE TITLE
NatronRender process often go to sleep

### ISSUE THREAD

**Issue by freesteel** [NatronGitHub/Natron#473] opened 2020-03-24 03:59 UTC
### Problem
When run Natron in command-line,process often go to sleep

Executing cmd `/opt/Natron-snap/NatronRenderer project.ntp`

The output is as follows

Py_SetPythonHome("/opt/Natron-snapshot/bin/..")
PYTHONPATH set to /opt/Natron-snapshot/bin/../lib/python27.zip:/opt/Natron-snapshot/bin/../lib/python2.7:/opt/Natron-snapshot/bin/../Plugins
Py_SetProgramName("/opt/Natron-snapshot/bin/NatronRenderer")
Py_Initialize()
PATH is /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/alidata/server/mysql/bin:/alidata/server/nginx/sbin:/alidata/server/php/sbin:/alidata/server/php/bin
PYTHONPATH is /opt/Natron-snapshot/bin/../lib/python27.zip:/opt/Natron-snapshot/bin/../lib/python2.7:/opt/Natron-snapshot/bin/../Plugins
PYTHONHOME is (null)
Py_DebugFlag is 0
Py_VerboseFlag is 0
Py_InteractiveFlag is 0
Py_InspectFlag is 0
Py_OptimizeFlag is 0
Py_NoSiteFlag is 0
Py_BytesWarningFlag is 0
Py_UseClassExceptionsFlag is 1
Py_FrozenFlag is 0
Py_TabcheckFlag is 0
Py_UnicodeFlag is 0
Py_IgnoreEnvironmentFlag is 0
Py_DivisionWarningFlag is 0
Py_DontWriteBytecodeFlag is 0
Py_NoUserSiteDirectory is 1
Py_GetProgramName is /opt/Natron-snapshot/bin/NatronRenderer
Py_GetPrefix is /opt/Natron-snapshot/bin/..
Py_GetExecPrefix is /opt/Natron-snapshot/bin/..
Py_GetProgramFullPath is /opt/Natron-snapshot/bin/NatronRenderer
Py_GetPath is /opt/Natron-snapshot/bin/../lib/python27.zip:/opt/Natron-snapshot/bin/../lib/python2.7:/opt/Natron-snapshot/bin/../Plugins:/opt/Natron-snapshot/bin/../lib/python27.zip:/opt/Natron-snapshot/bin/../lib/python2.7:/opt/Natron-snapshot/bin/../lib/python2.7/plat-linux2:/opt/Natron-snapshot/bin/../lib/python2.7/lib-tk:/opt/Natron-snapshot/bin/../lib/python2.7/lib-old:/opt/Natron-snapshot/bin/../lib/python2.7/lib-dynload
Py_GetPythonHome is /opt/Natron-snapshot/bin/..
Python library is in /opt/Natron-snapshot/lib/python2.7/site-packages
Restoring the image cache...
Loading plugin cache...
Info: init.py script not loaded (this is not an error)
Loading PyPlugs...
Loading project: /alidata/www/video_producer2/natron/projectConfigs/template5/project.ntp
writer ==> Rendering started
writer ==> Frame: 1, Progress: 0.4%, 2.0 Fps, Time Remaining: 2 minutes 3 seconds
writer ==> Frame: 2, Progress: 0.8%, 2.7 Fps, Time Remaining: 1 minute 32 seconds
writer ==> Frame: 3, Progress: 1.2%, 3.9 Fps, Time Remaining: 1 minute 2 seconds 
writer ==> Frame: 4, Progress: 1.6%, 4.0 Fps, Time Remaining: 1 minute 1 seconds
writer ==> Frame: 5, Progress: 2.0%, 4.6 Fps, Time Remaining: 53 seconds   

Process go to sleep 
Even if  wait a long time,  don't continue to output content

process stat
root   18647 75.6  8.2 3738620 1352228 pts/0 Sl+  11:29   0:21 /opt/Natron-2.3.15RC17/bin/NatronRenderer -b project.ntp

strace -p 18647
futex(0x390f98c, FUTEX_WAIT_PRIVATE, 1, NULL

### Versions
* **Natron version/commit**  Natron 2.3.15 RC17
* **OS version:** Ubuntu:16.04.5 LTS

### Steps to Reproduce

Natron [project](http://xyyxsns.oss-cn-shenzhen.aliyuncs.com/temporary/project.zip)

**Comment by rodlie** [comment] 2021-04-10 11:31
Still an issue? If possible try the latest beta.

**Comment by tebicap** [comment] 2021-04-22 18:26
I have the same issue on 2.4.0 and earlier. Please if there is a way to provide more information in somewhat, tell me.

my system:
  Os: Kubuntu 20.04, 64 bits
  processor: 4 x Intel Core i3-3240 CPU @ 3.40 GHz
  Mem: 5.8 GB of RAM

This is shown in the terminal:

life@life-desktop:~/_PROGRAMAS/Natron/Natron-2.4.0-Linux-64-no-installer$ ./NatronRenderer --writer Write2 --clear-cache --background "/home/life/Documentos/diseños varios/Un Rudo Despertar/CuantadelOmer21/cuentadelomer_día50.ntp"
Clearing the image cache...
Loading plugin cache...
Info: init.py script not loaded (this is not an error)
Loading PyPlugs...
Loading project: /media/life/Disco1/Documentos/diseños varios/Un Rudo Despertar/CuantadelOmer21/cuentadelomer_día50.ntp
Write2 ==> Rendering started
Write2 ==> Frame: 1, Progress: 0.1%, 3.8 Fps, Time Remaining: 4 minutes
Write2 ==> Frame: 2, Progress: 0.2%, 3.8 Fps, Time Remaining: 4 minutes
Write2 ==> Frame: 3, Progress: 0.3%, 5.7 Fps, Time Remaining: 3 minutes
Write2 ==> Frame: 4, Progress: 0.4%, 4.6 Fps, Time Remaining: 4 minutes
Write2 ==> Frame: 5, Progress: 0.4%, 5.7 Fps, Time Remaining: 3 minutes
Write2 ==> Frame: 6, Progress: 0.5%, 6.5 Fps, Time Remaining: 2 minutes 50 seconds
Write2 ==> Frame: 7, Progress: 0.6%, 7.3 Fps, Time Remaining: 2 minutes 32 seconds
Write2 ==> Frame: 8, Progress: 0.7%, 6.1 Fps, Time Remaining: 3 minutes           

--------here the process go to sleep.

This is the activity of the system:

![Screenshot_20210422_152507](https://user-images.githubusercontent.com/16892278/115766922-ecdc4f00-a37e-11eb-9cc0-c3879636797f.png)

**Comment by devernay** [comment] 2022-01-15 06:46
duplicate of #248

**Closed by devernay** 2022-01-15 06:46 UTC
Labels: func:engine, func:gui, type:bug, ver:2.x
