### ISSUE TITLE
Rotopaint automatically switches viewer inputs when painting

### ISSUE THREAD

**Issue by Shrinks99** [NatronGitHub/Natron#641] opened 2021-06-15 07:18 UTC
### Problem

When a paint stroke is created using the draw tool the Rotopaint node automatically switches the input of the viewer to itself regardless of what node the user has selected.

**Expected behavior:** The viewer does not change inputs so I can see what I'm painting

**Actual behavior:** The viewer input changes to the rotopaint node

### Steps to Reproduce

1. Create a rotopaint node and another node
2. View the second node
3. Try to paint using the rotopaint node while viewing the second node

https://user-images.githubusercontent.com/5672810/122008913-8b859a80-cd87-11eb-8ee4-2cdfb6627d98.mp4

### Versions

* **Natron version/commit:** 2.4
* **OS version:** Windows 10

**Comment by Shrinks99** [comment] 2021-06-15 07:29
Looks like this also _doesn't_ happen sometimes when working but the steps to reproduce should still work?  Kind of tricky to nail down the exact behavior. 😕

**Comment by batalooppak** [comment] 2021-09-06 20:02
I can always reproduce this (I'm in macOS). This bug it's annoying, because rotopaint it's use for beauty work and the workaround it's not ideal.

**Workaround:**
set first viewer node connection to the rotopaint node and a second connection to the node with the final result, and in the viewer change with connection number. (I'm not sure if I was clear enough)

<img width="374" alt="Screen Shot 2021-09-06 at 16 53 43" src="https://user-images.githubusercontent.com/906341/132257453-a643a3d3-d3d6-4cbe-8340-1f4776ed30da.png">

**Comment by bonalex01dev** [comment] 2021-09-19 18:45
Can't reproduce on win 10 natron 2.4beta2

**Comment by devernay** [comment] 2022-01-13 03:35
This happens only with the Draw tool/Clone/Blur/Brighter tools, not the Bezier tool.
This was actually a feature that was added because RotoPaint can be buggy sometimes and create glitches if not connected to the viewer.
I don't know if it is fixed, so I disabled the behavior, and added a button in RotoPaint to re-enable it:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/3778071/149261085-3794847f-6298-4e6b-9bc4-1188122a6b38.png">

**Comment by devernay** [comment] 2022-01-13 03:35
closed by https://github.com/NatronGitHub/Natron/commit/c907936fab1f6e9db1031d923b30450bf91f0e9b

**Closed as completed by devernay** 2022-01-13 03:35 UTC
Labels: func:gui, type:bug, func:roto, func:nodegraph, ver:2.x
