### ISSUE TITLE
(Bug):  Natron crashes on open

### ISSUE THREAD

**Issue by itsHyperMachines** [NatronGitHub/Natron#859] opened 2023-01-18 20:33 UTC
### Make sure to follow our issue report guidelines

- [X] I'm using the latest version of Natron (not required but recommended)
- [X] I've restarted Natron and the issue persists
- [ ] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [X] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [X] This bug is reproducible

### Natron version

Natron 2.5.0

### Operating system

Windows 10 21H2

### System specs

RAM: 16GB
CPU: Intel i5 6500
GPU: AMD Radeon 580

### Did you install Natron using the official installer?

- [X] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [ ] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### What were you trying to do?

I was trying to run Natron through the start menu shortcut and the .exe in the bin folder.

### What did you expect to happen? What happened instead?

I expected Natron to open without issue, but instead it opened as a background task for a few moments then closes.

### Step-by-step reproduction instructions

1. Start Natron

### Additional details

This is on a fresh install of Natron, I've never used it before and also don't know how to run it from the command line. I've seen the article "Natron in command-line" on the documentation page but still am unsure on how to run from the command line.

**Comment by savchenko** [comment] 2023-01-19 03:47
Might be AMD driver. Try reverting to the "basic video adapter" in the "device manager" and see if it launches.

**Comment by rodlie** [comment] 2023-01-19 07:49
It's the AMD driver. See https://github.com/NatronGitHub/Natron/issues/845#issuecomment-1328193825 for usable driver version.

Also a duplicate of https://github.com/NatronGitHub/Natron/issues/845. Close.

**Closed as completed by rodlie** 2023-01-19 07:49 UTC
Labels: type:bug
