### ISSUE TITLE
Invalid 'From' tag error when rendering on Windows if the system's decimal separator is not "."

### ISSUE THREAD

**Issue by Vombate9** [NatronGitHub/Natron#262] opened 2018-04-30 14:38 UTC
When I finished the project and placed a write node to render, it worked normally, but when I press the render button, I receive this message:

The specified transform file 'C:\Program Files\INRIA\Natron-2.3.10\Resources\OpenColorIO-Configs\blender\luts\rec709.spi1d' could not be loaded. Invalid 'From' tag.

Here is the Project file (no read nodes were used):
[Natron.zip](https://github.com/NatronGitHub/Natron/files/1960976/Natron.zip)

Here is a screenshot of the problem:
![natron error](https://user-images.githubusercontent.com/38860118/39431823-43820442-4c68-11e8-9297-ed1da83cbdb2.png)

Natron version: 2.3.10
OS version: Windows 10

**Comment by devernay** [comment] 2018-04-30 15:49
On your system, is the decimal separator "," instead of "." ?
i.e. do you write pi = 3,1416 or pi=3.1416 ?

**Comment by devernay** [comment] 2018-04-30 15:57
see https://github.com/imageworks/OpenColorIO/issues/297

**Comment by devernay** [comment] 2018-04-30 16:00
maybe duplicate of https://github.com/MrKepzie/Natron/issues/67 ?

**Comment by devernay** [comment] 2018-04-30 16:14
OK from the screenshot, you seem to be either Brasilian or Portuguese, so the problem is with the decimal separator. Can you test by setting the decimal separator to "." in the windows preferences?

**Comment by Vombate9** [comment] 2018-04-30 17:33
Changed the decimal separator and it worked. Thanks for the support.
Oh, and by the way, I am Brazilian. :)

**Comment by devernay** [comment] 2018-05-03 14:32
Notes:
- the error comes from here https://github.com/imageworks/OpenColorIO/blob/v1.1.0/src/core/FileFormatSpi1D.cpp#L131
- but the locale should be set by `AppManager::setApplicationLocale()` here: https://github.com/NatronGitHub/Natron/blob/2.3.10/Engine/AppManager.cpp#L793
- does that mean that `AppManager::setApplicationLocale()` is not called at the right time by the external render process?

**Comment by rodlie** [comment] 2020-07-14 15:31
Was going to look into this issue today, but I'm not able to replicate. I have Windows 10 Pro with UK English, I changed my locale to Norwegian (we have ,), but that did not trigger anything in Natron/OCIO. Are there anything else I need to do to trigger this?

**Comment by devernay** [comment] 2020-07-14 23:13
The only remaining check you could do is check if the bug was present in 2.3.10 / Windows 10, as when this issue was signaled.
If yes, and if it is fixed in 2.3.15, then we should close this issue.

**Comment by rodlie** [comment] 2020-07-14 23:24
Will try 2.3.10. We do however have a confirmed case on the forum https://discuss.pixls.us/t/error-libpng-warning-iccp-know-incorrect-srgb-profile/18978, that person was using 2.3.15, odd.

**Comment by efi** [comment] 2021-03-21 17:56
Hi. I am very new to this all and I can confirm that with `2.3.15` the problem exists on my German-locale Windows 10.

**Comment by devernay** [comment] 2021-03-21 17:59
Can you try with the latest beta? https://github.com/NatronGitHub/Natron/releases

**Comment by efi** [comment] 2021-03-21 18:12
> Can you try with the latest beta? https://github.com/NatronGitHub/Natron/releases

Sorry. Still doesn't work in the latest beta.

I removed the portable folder, unzipped the software, reverted the workaround back to my standard `,` as decimal separator, started Natron, opened my old project and got the same old error. 😞

**Comment by devernay** [comment] 2021-03-21 18:49
I just pushed https://github.com/NatronGitHub/openfx-io/commit/27a13e00db8bae1a31308d66b4039a3542c14805 which may fix it, but you'll have to wait for the next beta build (2.3.16beta3), which is usually produced by @rodlie

**Comment by efi** [comment] 2021-03-21 19:46
Thanks for the quick response!

I have found Natron not to be the right tool for me right now (missing audio features, trouble with centered-justified text overlays, ...) nevertheless it's remarkable what you guys created here.

When I can help to test this bugfix in the wild, just ping me when a build is ready.

**Closed** 2022-01-15 06:54 UTC
Labels: func:engine, prio:low, type:bug, status:confirmed
