### ISSUE TITLE
Natron has very high memory usage when play the video on view.

### ISSUE THREAD

**Issue by KingBaby** [NatronGitHub/Natron#325] opened 2019-02-09 04:15 UTC
### Problem
Natron has very high memory usage When I play the video in the view, it often take up 70% or more memory in my computer(the memory of my computer is 16GB). by the way, my natron often can't read the video currect, some frame would be crash(like the color mess up)

**Expected behavior:** Play the video during my work  with natron.

**Actual behavior:** 
Natron has very high memory usage, and return the message on the console as the following:
1. Missing key frame while searching for timestemp: 0
2. Cannot find  an index entry before timestemp: 0
3. illegal short term buffer state detected
4. Increasing reorder buffer to 4
5. Missing reference picture, default is 65542

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.3.14 Release.
* **OS version:** 
windows 7 Ultimate with Service Pack 1 x64

**Comment by threedslider** [comment] 2019-02-28 15:16
Can you make zip for Project files with video? Needed to reproduce in windows 10 if it is same bahavior ?

**Comment by devernay** [comment] 2019-05-11 16:19
duplicate of #333 
try reducing the number of threads, as indicated in #333 and post followup discussion in that issue.

Natron needs lots of RAM, especially if your CPU has many cores/threads.

**Closed by devernay** 2019-05-11 16:19 UTC
