### ISSUE TITLE
Cloned nodes causes Natron to crash

### ISSUE THREAD

**Issue by aeaeaeaeaeae** [NatronGitHub/Natron#579] opened 2021-02-25 13:12 UTC
### Problem

Natron crashes when using cloned node, in my case it's a cloned group node. There are two issues:

1. Natron crashes if I attempt to copy-paste the cloned group node.
2. Natron crashes if I try to open a project file with a cloned group inside.

I'm able to create cloned group nodes without Natron crashing. This is treacherous however, since saving and closing the projectfile will prevent Natron from reopening it.

[example.zip](https://github.com/NatronGitHub/Natron/files/6043082/example.zip)

Terminal printout when trying to open the example.zip file:
```
Restoring the image cache...
Loading plugin cache...
Info: init.py script not loaded (this is not an error)
Loading PyPlugs...
Loading project: <path_to_file>/example.ntp
Segmentation fault (core dumped)
```

### Steps to Reproduce

1. Create new group
2. Clone group
3. Ctrl-C group

Doing this in a new clean project will still let you reopen the projectfile even if you saved it at step 2., but with my provided example.npt file it will crash.

### Versions

* **Natron version:** Natron version 2.3.15 Release
* **OS version:** Ubuntu 20.04.1 LTS

**Comment by devernay** [comment] 2021-03-25 23:42
duplicate of #568

**Closed by devernay** 2021-03-25 23:42 UTC
