### ISSUE TITLE
IDKeyer Error

### ISSUE THREAD

**Issue by sus-unn** [NatronGitHub/Natron#274] opened 2018-05-21 11:54 UTC
### Problem

I had an IDKeyer node within my project, this made an following error:

**Expected behavior:**

No errors.

**Actual behavior:** [What actually happened]

Error log:
```
[20:45:11.915] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:33.654] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:46.882] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:49.524] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:49.681] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:49.765] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:52.325] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:52.377] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:52.457] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:52.500] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:52.571] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.

[20:45:53.062] IDKEY: Can not render: OpenGL 2.0 or GL_ARB_texture_non_power_of_two is required.
```
And nothing is working with IDKeyer node.

### Steps to Reproduce

1. Make few things with IDKeyer node. There are no errors before opening project file again.
2. When I open the project file, IDKeyer node makes an error.
3. And It is not working.
4. Every time I update the UI it makes an error again.

![image](https://user-images.githubusercontent.com/36620824/40306214-cd950b30-5d38-11e8-8573-a79f3894e9ca.png)
Screenshot of my node tree, this might help.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 
Natron version 2.3.11  fe372c9 
* **OS version:** 
on windows 10. x86-64.

**Comment by devernay** [comment] 2018-05-21 16:41
Probably a duplicate of https://github.com/NatronGitHub/Natron/issues/268

Can you please follow the instructions given at the top of https://github.com/NatronGitHub/Natron/issues/268 and post your results over there?

Do you have the same problems with the shadertoy node?

Note that I don't have Windows 10, so it's difficult to help.

**Closed by devernay** 2018-05-21 16:41 UTC
