### ISSUE TITLE
(Feature): Apple CPU M1 and Natron

### ISSUE THREAD

**Issue by snoopyonline78** [NatronGitHub/Natron#661] opened 2021-08-24 08:26 UTC
### 

- [X] I have read the [feature request guidelines](https://hackmd.io/@natron-dev-awesome/B1SW6Hbau)
- [X] I have followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [X] This feature is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Abug+type%3Afeature+type%3Aidea) and is not a duplicate

### Provide a description of your feature request

```markdown
Dear all,

is a version for Apple M1 Cpu planned?
How can i support Natron?
Is Natron active project in development and supported?

Kindly regards and sorry for the perhaps "Dummie" questions. I'm new in github :)

Thanks to all!
```

### Is this a realistically implementable feature?

- [ ] My feature is realistically implementable
- [ ] My feature is NOT realistically implementable

### Can you contribute in creating this feature?

- [X] I am unable, or not willing to contribute to creating this feature
- [ ] I am able and willing to contribute to the creation of this feature

**Comment by rodlie** [comment] 2021-08-24 08:30
Hi,

> is a version for Apple M1 Cpu planned?

please see https://github.com/NatronGitHub/Natron/issues/607

> How can i support Natron?

developers are always needed.

> Is Natron active project in development and supported?

Yes.

**Comment by snoopyonline78** [comment] 2021-08-24 08:31
wow. Thanks a lot!!!!

**Comment by devernay** [comment] 2021-08-28 17:58
duplicate of #607

**Closed as completed by devernay** 2021-08-28 17:58 UTC
