### ISSUE TITLE
Natron doesn't start

### ISSUE THREAD

**Issue by dilom** [NatronGitHub/Natron#326] opened 2019-02-23 05:49 UTC
It seems that several people experience the same issue. I have exactly the same error message as referenced bellow, only difference is I am under Fedora.
Any ideas?

Hi , I'm in manjaro Linux KDE 18.0.2 and Natron portable or installed doesn't start here.
`Natron Version 2.3.14
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
couldn't open library /home/ebarranco/Natron2/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /usr/lib/libcairo.so.2: undefined 
Caught segmentation fault (SIGSEGV) from thread Main(0x322f9d0), faulty address is 0x366a0 from 0x366a0
`

_Originally posted by @ebarranco in https://github.com/NatronGitHub/Natron/issues/317#issuecomment-460091606_

**Comment by devernay** [comment] 2019-02-23 06:57
thank you, but this is a duplicate of #317 
please add a comment to an existing issue rather that create a duplicate

**Closed by devernay** 2019-02-23 06:57 UTC
