### ISSUE TITLE
Segmentation fault on startup (libfreetype.so.6)

### ISSUE THREAD

**Issue by p2or** [NatronGitHub/Natron#385] opened 2019-07-01 14:49 UTC
Hey guys,

unfortunately I'm getting the following *segmentation fault* when running the latest release on _Arch Linux (Manjaro 64bit)_. However, removing  `libfreetype.so.6` temporarily (when running _Natron_ the first time) gets _Natron_ to start properly. 

### Console Output

> couldn't open library /home/<user>/Natron-2.3.14-Linux-x86_64bit/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /usr/lib/libcairo.so.2: undefined symbol: FT_Done_MM_Var
> Caught segmentation fault (SIGSEGV) from thread Main(0x33fb9d0), faulty address is 0x366a0 from 0x366a0

### Steps to Reproduce

1. Install Natron using *Portable* or *Installer* versions on _Arch Linux_
2. Start Natron
3. Segmentation fault

### Workaround

1. Temporarily remove `libfreetype.so.6` from `lib` folder
2. Start Natron 
3. Copy `libfreetype.so.6` back into the `lib` folder

### Versions

Natron version 2.3.14 Release

Cheers,
Christian

**Comment by rodlie** [comment] 2019-07-01 15:01
Known issue. The Natron 2.3.14 Linux binaries has several broken symlinks in IO.ofx and Arena.ofx, this means system libraries are used and Natron will run in to various issues depending on the distro your are running.

You can see the broken symlinks in  ``NATRON_FOLDER/Plugins/OFX/Natron/Arena.ofx.bundle/Libraries`` and ``NATRON_FOLDER/Plugins/OFX/Natron/IO.ofx.bundle/Libraries``

This has been fixed and will be part of 2.3.15.

*Your specific issue can be traced back to the broken libcairo symlink in Arena.ofx.*

**Comment by p2or** [comment] 2019-07-01 15:11
Thanks for your quick reply @rodlie. Cool, looking forward to it.

**Comment by devernay** [comment] 2019-07-02 16:36
We could make a hotfix script that repairs the broken links in the 2.3.14 install.

@rodlie can you work on that? That would be super helpful

You can find all the broken links using `find . -type l ! -exec test -e {} \; -print`

It would be a script that is given the toplevel Natron installation dir as a single argument.

**Comment by devernay** [comment] 2019-07-02 16:38
duplicate of #342

**Closed by devernay** 2019-07-02 16:38 UTC
Labels: difficulty:easy, prio:high, status:confirmed
